### ISSUE TITLE
Support --format=summary when diffing a collection

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/restful#80]
When diffing a large collection, the amount of output can be too much process.

With a `--format=summary` argument, we could present a summary of the difference to the end user, empowering them to better understand the differences.

From #75, #56

**Comment by diablodale** [comment]
Caution --format is not a safe parameter name to use for **diff** or for **generate**.
Why?
Because format is a common name for arguments in core WP REST. Easy example is for posts.
Posts have a non-required argument "format" for the POST method endpoint like this:
```
"format": {
  "required": false,
  "enum": ["standard",
    "aside",
    "image",
    "video",
    "quote",
    "link",
    "gallery",
    "audio"],
  "description": "The format for the object.",
  "type": "string"
}
```

I recommend to change everywhere this wp-cli --format parameter to something else.
I recommend "--outputformat" and it to be changed throughout the code, e.g. in generate, diff, get, list, ...

**Comment by diablodale** [comment]
related #95
