### ISSUE TITLE
Strongly consider the implications of using HTTP status headers as return codes.

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/restful#96]
In #92, the return logic became:

```
if ( ( $status < 400 ) && ( isset( $body['previous']['id'] ) || isset( $body['id'] ) ) ) {
 +				// handles cases where user forget to put a value for --force=<value>
 +				WP_CLI::line( isset( $body['previous'] ) ? $body['previous']['id'] : $body['id'] );
 +			} else {
 +				WP_CLI::halt( $status );
 +			}
```

We should come to a final determination of whether this implementation makes sense.

cc @diablodale

**Comment by diablodale** [comment]
Caution: The code I've written returns http status codes via errors code in the code above and in other areas. It also leverages the wp_error class which also uses http status codes. In restful, everything is (or should) be an http status code....because it is REST over HTTP.

I have need at the command line to know the http status code for a wp-cli rest xxxxx.
I need to know the distinction between a 401 and a 403; former needs credentials, latter needs authorization alerts. The event handlers which are calling wp-cli will do different things depending on the specific status codes returned as well as text or porcelain.

Remember that return codes are a single byte. Very quickly we get wraparound as the most interesting codes are: 200, 4xx, 5xx.  I've already checked. None of the http status codes resolve to the same place in the 0-255 range. Technically though...it is possible.

If not to return the http status code (which is done automatically and free for us), then I would propose maintaining a static mapping of http status codes -> restful error codes. And then to enforce in this project as a code rule to always call a mapping function to get the return code. This approach creates a four part burden: maintaining the map of codes, maintaining the function which maps the codes, coders to always use the mapping function, and code reviewers to check that coders are using the mapping function.

**Comment by danielbachhuber** [comment]
> I have need at the command line to know the http status code for a wp-cli rest xxxxx.
> I need to know the distinction between a 401 and a 403; former needs credentials, latter needs authorization alerts. The event handlers which are calling wp-cli will do different things depending on the specific status codes returned as well as text or porcelain.

What if we had a `--format=<format>` that returned the resource id and / or http status code, and reserved CLI return codes for RESTful WP-CLI (e.g. framework operations)?

> Remember that return codes are a single byte. Very quickly we get wraparound as the most interesting codes are: 200, 4xx, 5xx. I've already checked. None of the http status codes resolve to the same place in the 0-255 range. Technically though...it is possible.

Yeah, I don't think the concept translates directly.

**Comment by diablodale** [comment]
I want the error text *and* the http status code. They are both very useful.
I believe a tool which provides only 0 or 1 as a return code is a disservice to customers. We are now in the times of chains of automations and having more specificity than BAD/GOOD is important.
Luckily, we can always honor the 0 as good. And non-zero as bad.  Its the kinds of bad which are needed in today's toolchains.

I recommend then the static mapping. Its a maintenance burden, but it satisfied the needs of today's toolchains while not suffering from some future errorcode conflict.

**Comment by danielbachhuber** [comment]
> I recommend then the static mapping. Its a maintenance burden, but it satisfied the needs of today's toolchains while not suffering from some future errorcode conflict.

I'm amenable to this. HTTP status codes don't change very often.

**Comment by diablodale** [comment]
What about a class just for this.
- has private somethings (const, array, ...) that holds a mapping from http status code -> restful exit code.
- has static public function that given an integer http status code, returns an integer exit code
- has static public function that given a specific class (e.g. WP_Error) will transform any http status code to be an integer exit code
- any unknown classes or other argument types, will throw an exception

What's your opinion on this case?
- any unknown/missing mapping of http status code -> restful exit code will ???????

Since it could be a good 2xx scenario yet the current version of restful doesn't yet have the mapping...I hesitate in throwing an exception that would halt execution. I lean more towards a non-halting notice + returning a fallback error code used only for no-mapping-available scenarios.

**Comment by danielbachhuber** [comment]
> What about a class just for this.

👍 

> any unknown/missing mapping of http status code -> restful exit code will ???????

I'd think `>=400` would be `1`, and `2xx` and `3xx` would be `0`.

**Comment by diablodale** [comment]
draft proposed mapping and rules at https://docs.google.com/spreadsheets/d/1low5ctE4GT9T-s86Yv3zfsZjStJ9CnvqywbcF5TvUvM/edit?usp=sharing

**Comment by danielbachhuber** [comment]
Pull request was declined.
